export const ICONS = {
  instagram: { label: 'Instagram', className: 'fa-brands fa-instagram', color: '#D6336C' },
  youtube: { label: 'YouTube', className: 'fa-brands fa-youtube', color: '#FF3B30' },
  whatsapp: { label: 'WhatsApp', className: 'fa-brands fa-whatsapp', color: '#25D366' },
  snapchat: { label: 'Snapchat', className: 'fa-brands fa-snapchat', color: '#FFFC00' },
  tiktok: { label: 'TikTok', className: 'fa-brands fa-tiktok', color: '#111111' },
  twitter: { label: 'Twitter / X', className: 'fa-brands fa-x-twitter', color: '#111111' },
  facebook: { label: 'Facebook', className: 'fa-brands fa-facebook', color: '#1877F2' },
  linkedin: { label: 'LinkedIn', className: 'fa-brands fa-linkedin', color: '#0A66C2' },
  threads: { label: 'Threads', className: 'fa-brands fa-threads', color: '#000000' },
  pinterest: { label: 'Pinterest', className: 'fa-brands fa-pinterest', color: '#E60023' },
  reddit: { label: 'Reddit', className: 'fa-brands fa-reddit', color: '#FF4500' },
  discord: { label: 'Discord', className: 'fa-brands fa-discord', color: '#5865F2' },
  telegram: { label: 'Telegram', className: 'fa-brands fa-telegram', color: '#24A1DE' },
  spotify: { label: 'Spotify', className: 'fa-brands fa-spotify', color: '#1DB954' },
  applemusic: { label: 'Apple Music', className: 'fa-brands fa-apple', color: '#FA243C' },
  soundcloud: { label: 'SoundCloud', className: 'fa-brands fa-soundcloud', color: '#FF5500' },
  twitch: { label: 'Twitch', className: 'fa-brands fa-twitch', color: '#9146FF' },
  kick: { label: 'Kick', className: 'fa-solid fa-gamepad', color: '#53FC18' },
  patreon: { label: 'Patreon', className: 'fa-brands fa-patreon', color: '#FF424D' },
  substack: { label: 'Substack', className: 'fa-solid fa-bookmark', color: '#FF6719' },
  medium: { label: 'Medium', className: 'fa-brands fa-medium', color: '#000000' },
  github: { label: 'GitHub', className: 'fa-brands fa-github', color: '#24292E' },
  paypal: { label: 'PayPal', className: 'fa-brands fa-paypal', color: '#00457C' },
  cashapp: { label: 'Cash App', className: 'fa-solid fa-dollar-sign', color: '#00D632' },
  venmo: { label: 'Venmo', className: 'fa-solid fa-v', color: '#008CFF' },
  store: { label: 'Store / Shop', className: 'fa-solid fa-bag-shopping', color: '#E11D48' },
  email: { label: 'Email', className: 'fa-regular fa-envelope', color: '#52685C' },
  phone: { label: 'Phone', className: 'fa-solid fa-phone', color: '#16A34A' },
  trending: { label: 'Broker / Finance', className: 'fa-solid fa-arrow-trend-up', color: '#14A866' },
  globe: { label: 'Website', className: 'fa-solid fa-globe', color: '#0E7A46' },
  link: { label: 'Other Link', className: 'fa-solid fa-link', color: '#52685C' },
};

export const ICON_KEYS = Object.keys(ICONS);
